### Aprenda como usar o Numpy

In [1]:
import numpy as np
a = np.array([1,2,3])

In [2]:
print(a)

[1 2 3]


In [4]:
b = np.array([(2,5,7),(5,3,9)])

In [5]:
print(b)

[[2 5 7]
 [5 3 9]]


In [6]:
c = np.ones((4,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
d = np.eye(10)

In [12]:
print(d)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
b.max()

9

In [14]:
b.min()

2

In [15]:
b.sum()

31

In [16]:
b.mean()

5.166666666666667

In [17]:
b.std()

2.3392781412697